apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: mangesh22898/checkout-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
